### PR TITLE
added group raytrashing

### PR DESCRIPTION
**Pull request by SBK78MC**

### CODE REVIEW

**Comment by ltratt** [comment]
Ready to merge?

**Comment by SBK78MC** [comment]
Hi, yes we are ready. But we recognized Mann, Pavandeep Singh (pavandeep.mann@kcl.ac.uk) has the status "Withdrawn".

**Comment by ltratt** [comment]
Yes, though sometimes those records don't reflect the actual situation (there's a time lag). Have you contacted / heard from this person?

**Comment by SBK78MC** [comment]
Yes, we contacted him, but we haven't got a response yet.

**Comment by ltratt** [comment]
OK, I'm going to merge this as-is. If you haven't heard anything by 17:00 on Monday, please raise another PR removing him from this group.

**Pull request merged**
